#! /bin/bash

specruptiva() (

  set -eu

  _err() {
    >&2 echo "$@"
    exit 1
  }

  _get_root() {
    echo "$(readlink -f "$(dirname "$BASH_SOURCE")"/..)"
  }

  _help() {
    cat <<-EOM
  
  NAME
      specruptiva  -- outils de gestion centré sur les données

  SYNOPSIS
      specruptiva validate SCHEMA_FILE DATA_FILE   # valide que le fichier de données
                                                   #   est conforme au fichier schema

      specruptiva build-wasm 
      specruptiva start-server
EOM

  }

  _validate() {
    ROOT=$(_get_root)
    go run $ROOT/cmd/cli/main.go ${@:-}
  }

  _buildwasm() {
    ROOT=$(_get_root)
    rm -f $ROOT/assets/json.wasm $ROOT/assets/wasm_exec.js
    GOOS=js GOARCH=wasm go build -o $ROOT/assets/json.wasm $ROOT/cmd/wasm/main.go
    cp $(go env GOROOT)/lib/wasm/wasm_exec.js $ROOT/assets/.
  }

  _startserver() {
    _buildwasm
    ROOT=$(_get_root)
    go run $ROOT/cmd/server/main.go
  }

  case "${1:-}" in
  "--help" | "")
    _help
    ;;
  validate | vet)
    _validate ${@:2}
    ;;
  build-wasm)
    _buildwasm
    ;;
  start-server)
    _startserver
    ;;
  *)
    _err "La commande '${1:-}' est inconnue"
    ;;

  esac
)

[ "$0" != "$BASH_SOURCE" ] || specruptiva "$@"
